export const tokens = {
  colors: {
    background: '#F8F5EF',
    backgroundAlt: '#EFE8DC',
    surface: '#FFFFFF',
    surfaceWarm: '#FFF9F0',
    surfaceMuted: '#F3EEE5',
    primary: '#2F6F4E',
    primaryMuted: '#DDEBDD',
    primaryStrong: '#214D37',
    accent: '#D9673F',
    accentMuted: '#F8DFD4',
    citrus: '#E7A93B',
    citrusMuted: '#F8EAC7',
    text: '#201A16',
    textSecondary: '#6F6258',
    textMuted: '#9B8C80',
    border: '#E4D8C9',
    borderStrong: '#CDBEAC',
    success: '#2F8F55',
    error: '#B23B2B',
    errorMuted: '#F8DED8',
    skeleton: '#E8DED1',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 22,
    xxl: 28,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 24,
    full: 9999,
  },
  shadow: {
    card: {
      shadowColor: '#2B2118',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 3,
    },
    floating: {
      shadowColor: '#2B2118',
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.14,
      shadowRadius: 28,
      elevation: 6,
    },
  },
  layout: {
    maxContentWidth: 1120,
    maxReadableWidth: 760,
    sideRailWidth: 320,
    tabletBreakpoint: 720,
    desktopBreakpoint: 1024,
  },
  lineHeight: {
    tight: 1.2,
    normal: 1.5,
    relaxed: 1.75,
  },
} as const;

export type Tokens = typeof tokens;
